### ISSUE TITLE
KDE Connect

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#28]
There is an Android app KDE Connect which connects to the Linux PC (which has kde-connect installed and running). When I open remote control in Android KDE Connect, it shows Goggles with an empty name and empty song. I attach an example of another app, where the info is visible.
![screenshot_2015-03-04-13-10-40](https://cloud.githubusercontent.com/assets/591932/6482647/bc024470-c270-11e4-8439-7a373ddb0f37.png)
![screenshot_2015-03-04-13-10-49](https://cloud.githubusercontent.com/assets/591932/6482648/c055c736-c270-11e4-9643-1f61ec1fe837.png)

**Comment by gogglesguy** [comment]
So I'm not sure how to debug kdeconnect. Looking at the console output of kdeconnect, I'm seeing the following:

MprisControlPlugin::addPlayer: Mpris addPlayer "org.mpris.MediaPlayer2.gogglesmm" -> ""

This looks like it never received the Identity property from the mpris dbus interface (the empty quotes should have been "Goggles Music Manager", though from my own logs, that has been send just fine. Since gogglesmm shows up just alright in mpristester (https://github.com/randomguy3/mpristester), I suspect there's something wrong with kdeconnect.

**Comment by gogglesguy** [comment]
For reference: https://bugs.kde.org/show_bug.cgi?id=344837

**Comment by gogglesguy** [comment]
Need to correctly implement DBus Properties Interface. It should return Variants.

**Comment by gogglesguy** [comment]
There's a fix on the develop branch if you like to try.

**Comment by nerijus** [comment]
Yes, it works now, thanks!

**Comment by nerijus** [comment]
One problem though - when I unlock Android screen, the info is not visible. But if I press pause it becomes visible and is visible until I lock and unlock screen again.
It could be my setup problem - KDE Connect is 0.8 on Android and 0.7 on Linux PC.

**Comment by gogglesguy** [comment]
I noticed that as well, but I think the same thing happened with another music player (if you can confirm?). I couldn't find anything else that would have been caused by gogglesmm.

**Comment by nerijus** [comment]
Yes, IIRC I saw it with other player too.

**Comment by nerijus** [comment]
But if you have it with 0.8 Linux version, I think it is worth reporting to the kde connect people (there were a bug report link above but it's no longer here).

**Comment by gogglesguy** [comment]
I closed the earlier kdeconnect bugreport since it wasn't a bug in kdeconnect but in gogglesmm. I have 0.8 client and server and same thing happens with Rhythmbox. If you care to pursue it, I suggest you file the bug report with kdeconnect.
