### ISSUE TITLE
Album grouping seems to depend on Artist

### ISSUE THREAD

**Issue by sophom** [gogglesmm/gogglesmm#39]
I'm not sure if this is a bug or a feature but it is confusing.

On some compilation albums that have different artists listed for each individual track,  gmm creates a different album with the same title per artist as opposed to just creating one album. I would prefer the later. If I view the tags on gmm I see the individual artist on both the artist field and the album artist field. If I open the same file in easytag only the artist tag is present and the album artist tag is blank. 

Is there a way for me to either merge the albums together or get gmm to do it when it syncs? I apologize if this has been addressed before.

**Comment by gogglesguy** [comment]
Album grouping is done based on album and album artist. If no album artist is set, it will automatically set it to the value of the artist tag. 

To get proper grouping you'll need to adjust the album artist tag on your compilation albums so that all tracks on the album have the same album name and album artist. 

There's currently no way to automatically 'fix' this during sync. I think some other players may have alternative strategies during import (like group under same album for all files in same directory, but I'm not sure if that always works either). I find the album artist strategy to work pretty well for me. I have a lot of soundtracks myself and use the album artist extensively.

You can adjust the album artist in the track editor, simply select all tracks that need to be merged, right click to edit. Once you have adjusted the album artist they should have been grouped under the same album. Make sure to save it to the tag itself so that next time you import you won't have to redo it. 

If you forget to select save to tag during edit, simply reselect all the tracks again, right click to edit, select save to tag and click save. I use this a lot myself, making lots of minor edits before batch saving everything to the tags.

Of course you can also edit album artist in easytag and reimport/sync the files back into gogglesmm.

Hope this helps!

**Comment by sophom** [comment]
Yes. That works. I'll start correcting things... Thank you!

**Comment by sophom** [comment]
Oh... Hang on. I just started fixing some and now I'm noticing something related but slightly different. I have several albums I got from emusic and I think they used some old form of VBR. I say this because under format, I see a variety of varying entries such as mp3 128 kbps 44.1 kHz, mp3 0 kbps 44.1 kHz, mp3 352 kbps 44.1 kHz,  mp3 416 kbps __48 kHz__ etc... Also the song times are messed up. For example the one with 0 kbps comes up as having a duration 0:00. When I actually start playing it plays fine and the time left is correct after the first second or so. BTW non of these are 48kHz... 




![gmm_format](https://cloud.githubusercontent.com/assets/11645950/12220011/ed44c748-b729-11e5-9a6c-cf3054b3bbe7.png)

**Comment by gogglesguy** [comment]
To support compilation albums in library music managers well, the only way is to be very explicit and specify the album artist / compilation in your tag. Otherwise it's just guesswork for the player and it may pick a stragety that works great for some people and totally won't work for others.

That said, I'm not against revising the import strategy to make it even better or have some options to tweak for various file system layout, but in the end it still be guesswork for files without the compilation/album artist tag :)

**Comment by gogglesguy** [comment]
Ah right, so recently I've added album grouping based on the sample rate and channel count. This should work well as long as taglib can determine the proper audio format. I guess mp3 can be notoriously broken especially if noncompliant editors may have been used in the past.

If you want feel free to send me one of the mp3s by email and I can take a look at it and see what horrible things have been done to it.

Alternatively, you can take a look at them with MP3Diag and see if it can fix it for you: http://mp3diags.sourceforge.net

**Comment by sophom** [comment]
Well... Just a thought... but what if in the Track tab of Sync Folder there was an option to "Group tracks in a directory with the same Album tag together in a single album"? Ignore format and Album Artist in this case... Or even better if all the Artist tags are the same use that as the Album Artist and if they are different use "Various Artists". I don't know what to do about this format thing

**Comment by gogglesguy** [comment]
Thanks for the feedback @sophom. See followup tickets #40 and #42.
