### ISSUE TITLE
Add option to disable album grouping by audioformat

### ISSUE THREAD

**Issue by gogglesguy** [gogglesmm/gogglesmm#40]
Some highly malformed mp3s may not give accurate audioformat information by taglib which messes up the album grouping based on the audioformat. A import option to disable this grouping should help those users with lots of crappy files. See issue #39

**Comment by sophom** [comment]
I just tried this. Thank you!

It works great if you import your collection from scratch so long as you remember to uncheck the "Group albums by audio format". In other works if there is no goggles.db in the .local/share/gogglesmm directory. Unfortunately there was a gogglesdb in my gogglesmm directory. 

If, instead of re-importing the whole thing from scratch, you try to  sync everything  using "Sync Folder" it does not work. This is what I tried first because I don't want to re-enter my internet radio stations. Again If you uncheck the option "Group albums by audio format" the sync ends extremely fast and it's as if nothing happened. The older album entries that were binned according to format do not get removed from the db and there is no new entry for an album that contains all the tracks.

As a side note... I initially did a git pull and an incremental build. When I tried to sync after this I got  a segfault. I then did make clean and rebuilt and did not get the segfault.

**Comment by gogglesguy** [comment]
When you Sync'ed the folder, did you check the "Updated Existing Tracks" -> "All" option? Because if "modified since last import" is selected it won't probably do anything since none of you files were updated outside of gogglesmm.

Not too worried about the crash if a clean build did not crash. Eventually the build system will be upgraded to cmake.

**Comment by sophom** [comment]
OK. sync does work. I did indeed had to select the "All" option which I had not. I had a copy of my old db, restored it and reran sync with the  "Updated Existing Tracks" -> "All"  set. Thanks!

**Comment by gogglesguy** [comment]
@sophom thanks for testing!

**Comment by gogglesguy** [comment]
Available in https://github.com/gogglesmm/gogglesmm/releases/tag/1.0.10
