### ISSUE TITLE
About dialog: ALAC decoder licensed under MIT

### ISSUE THREAD

**Issue by hartwork** [gogglesmm/gogglesmm#72]
Hi!

In the about dialog the note on ALAC decoder "All rights reserved" caught my attention, so I went to [the code](https://github.com/gogglesmm/gogglesmm/blob/53f264a252a32ef9a9a5e04fb3537a36e2a2c26e/gap/lib/alac/alac.c) and compared the license header to find out: That's [the MIT license](https://opensource.org/licenses/MIT), which is a lot better than "All rights reserved" from the users point of view.
Could you make the dialog say "MIT license"? It would save users to research that again and also confusion (because _true_ "All rights reserved" would have been incompatible with the GPL).

Thanks and best, Sebastian

**Comment by gogglesguy** [comment]
"All rights reserved" is a bit of an obsolete term in regards to copyright, but since it is included in the original work I'm keeping it. I consider the About dialog merely a summary of the actual licensing information, for complete details one should consult the actual source code, which is how the actual program is distributed.

Nonetheless I'll see if I can fit in a MIT statement.
